apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    tier: node
    k8s-app: kube-proxy
spec:
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: gcr.io/google_containers/hyperkube:v1.11.1
        command:
        - ./hyperkube
        - proxy
        - --master=https://{K8_M1}:443
        - --kubeconfig=/etc/ssl/etcd/ssl/kubeconfig.yaml
        - --logtostderr=true
        - --proxy-mode=iptables
        - --masquerade-all
        - --hostname-override={K8_M1}
        - --cluster-cidr=10.20.0.0/20
        - --v=3
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - name: kube-ssl
          mountPath: /etc/ssl/etcd/ssl
          readOnly: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
        name: ssl-certs-host
      - name: kube-ssl
        hostPath:
          path: /etc/ssl/etcd/ssl
