apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://{K8_M1}:443
    certificate-authority: /etc/ssl/etcd/ssl/ca.pem
users:
- name: kubelet
  user:
    client-certificate: /etc/ssl/etcd/ssl/member-labs-k8s-master-01.pem
    client-key: /etc/ssl/etcd/ssl/member-labs-k8s-master-01-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
